### PR TITLE
This add a map on the contact row

### PR DESCRIPTION
**Pull request by ponsfrilus**
image

### CODE REVIEW

**Comment by dalgetty** [comment]
awesome !

**Comment by ponsfrilus** [comment]
@dalgetty yes but the right padding is removed for this one... If you think it's ok, let me know...

**Comment by dalgetty** [comment]
So long as the three boxes are responsively dropping one under another, no problem

**Comment by ponsfrilus** [comment]
image

That looks good enough to me. What about you guys @dalgetty @alexwiderski @domq ?

**Comment by domq** [comment]
@ponsfrilus Sweet!

**Comment by ponsfrilus** [comment]
Merged based on comments, not reviews.

**Pull request closed without merging**
